website_base_url = "http://localhost:8080"  # This will be used to dynamically make the redirect url internally.
login_url = "/login"  # The url or route used to prompt the user to login.
routes = [ "frontend", "backend", ]  # These routes `/website/<filename>` will have their `routes` variable imported which will be loaded into the bot's route table.
oauth_scopes = [ "identify", ]  # The scopes that should be added to the automatic login url.
user_agent = ""  # A user agent to use for the application

# Data for the StreamElements API
[streamelements]
    token = ""

# Data for the Twitch oauth login
[twitch]
    client_id = ""  # https://dev.twitch.tv/console/apps
    client_secret = ""

# Data for the YouTube playlist auto-generation
[google]
    api_key = ""
    valid_playlists = [
        "UUJZcsYCqoQ13KtCtApTfLaQ",
    ]  # A list of playlist IDs

# Used for the bot's invite and login links.
[oauth]
    client_id = ""
    client_secret = ""

# This data is passed directly over to asyncpg.connect().
[database]
    type = "postgres"  # postgres, sqlite, mysql
    enabled = true
    user = ""
    password = ""
    database = "database"
    host = "127.0.0.1"
    port = 5432
